### ISSUE TITLE
Add button to calibrate motors so that field-oriented driving is driver-friendly

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCode2021#25]
There should be a button that allows the driver to set the current direction as "forward" so that when the driver tries to move forward in field-oriented mode, they will always move in the currently designated "forward" direction.

In addition, field-oriented drive should be the default driving mode.

**Comment by 0sani** [comment]
Fixed in commit [caa8ed5c563d1e7dc53d727455acfd5418804b0c](https://github.com/DeepBlueRobotics/RobotCode2021/commit/caa8ed5c563d1e7dc53d727455acfd5418804b0c)
