### ISSUE TITLE
Wait for CANCoders to initialize before calling HomeAbsolute

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCode2021#9]

**Comment by alexander-mcdowell** [comment]
We are no longer using HomeAbsolute so we can just remove all references entirely.

**Comment by 0sani** [comment]
Fixed in commit [4360841dada279ebe2e1f12af6fcbf21431cc980](https://github.com/DeepBlueRobotics/RobotCode2021/commit/4360841dada279ebe2e1f12af6fcbf21431cc980)
